name: Android Release Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant permissions
        run: chmod +x gradlew

      - name: Build Debug APK
        # assembleDebug is used to ensure the APK is signed with a debug key for easy installation
        run: ./gradlew assembleDebug -Pandroid.quiet=true

      - name: Rename and Move
        run: |
          APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          mv "$APK_PATH" SimpleKeyboard_EnglishOnly.apk

      - name: Upload to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "SimpleKeyboard_EnglishOnly.apk"
          tag: "v1.0-eng"
          name: "English Only Build"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
